let grade = 80;
if (grade >= 90)
    console.log('A')

else if (grade >=80 && grade < 90)
    console.log('B')
else if (grade >= 70 && grade < 80)
    console.log('c')
else if (grade >=60 && grade < 70)
    console.log('D')
else if (grade >=50 && grade < 60)
    console.log('E')
else if (grade >= 50 && grade >= 0)
    console.log('F')
else (grade = false)
